stages:
  - lint
  - test
  - build_and_push

variables:
  GO_VERSION: "1.24"
  API_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/sharingan-api"

.api:
  only:
    refs:
      - main
      - develop

lint_api:
  extends: .api
  stage: lint
  image: golangci/golangci-lint:latest
  script:
    - cd api
    - golangci-lint run ./api/...

test_api:
  extends: .api
  stage: test
  image: golang:${GO_VERSION}
  script:
    - cd api
    - go mod tidy
    - go test -v ./...

build_and_push_api:
  extends: .api
  stage: build_and_push
  image: docker:latest
  services:
    - name: docker:dind
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - source ./api/API_VERSION.txt
    - docker build -t $API_IMAGE_NAME:latest ./api
    - docker tag $API_IMAGE_NAME:latest $API_IMAGE_NAME:$API_VERSION
    - docker images
    - docker push $API_IMAGE_NAME:latest
    - docker push $API_IMAGE_NAME:$API_VERSION
