root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # First generate swagger docs, then build the application
  cmd = "swag init -g ./cmd/main.go -o api/docs && go build -o ./tmp/main ./cmd/main.go"
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "api/docs"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = [".env"]


  # Add this to ensure docs are fully generated before starting the app
  full_bin = "./tmp/main"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
