stages:
  - lint
  - test
  - build
  - push

variables:
  GO_VERSION: "1.24"
  IMAGE_NAME: "15932/sharingan-api"

lint:
  stage: lint
  image: golangci/golangci-lint:latest
  script:
    - golangci-lint run ./...

test:
  stage: test
  image: golang:${GO_VERSION}
  script:
    - go mod tidy
    - go test -v ./...


build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
    - source VERSION.txt
  script:

    - docker build -t $IMAGE_NAME:latest .
    - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$VERSION
    - docker save -o "$IMAGE_NAME-$VERSION.tar" $IMAGE_NAME:$VERSION
  artifacts:
    name: "$CI_PROJECT_NAME-$VERSION"
    paths:
      - "$IMAGE_NAME-$VERSION.tar"
  only:
    - main
    - develop


push_to_registry:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
    - source VERSION.txt
  script:
    - docker load < "$IMAGE_NAME-$VERSION.tar"
    - docker push $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$VERSION
  only:
    - main
    - develop